[meta]
version = 2026.6
description = "nnn (n³) is a full-featured terminal file manager. It's tiny, nearly 0-config and incredibly fast."
name = "nnn"
[package]
source = "git clone https://github.com/squidowl/halloy"
command = "cargo build --release"
finbin = "halloy"